import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Regular font
const PretendardRegular = localFont({
  src: [
    {
      path: "./fonts/Pretendard-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-PretendardRegular",
});

// Medium font
const PretendardMedium = localFont({
  src: [
    {
      path: "./fonts/Pretendard-Medium.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-PretendardMedium",
});

// Bold font
const PretendardBold = localFont({
  src: [
    {
      path: "./fonts/Pretendard-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-PretendardBold",
});

// Black font
const PretendardBlack = localFont({
  src: [
    {
      path: "./fonts/Pretendard-Black.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-PretendardBlack",
});

// ExtraBold font
const PretendardExtraBold = localFont({
  src: [
    {
      path: "./fonts/Pretendard-ExtraBold.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-PretendardExtraBold",
});

// ExtraLight font
const PretendardExtraLight = localFont({
  src: [
    {
      path: "./fonts/Pretendard-ExtraLight.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-PretendardExtraLight",
});

// Light font
const PretendardLight = localFont({
  src: [
    {
      path: "./fonts/Pretendard-Light.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-PretendardLight",
});

// SemiBold font
const PretendardSemiBold = localFont({
  src: [
    {
      path: "./fonts/Pretendard-SemiBold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-PretendardSemiBold",
});

// Thin font
const PretendardThin = localFont({
  src: [
    {
      path: "./fonts/Pretendard-Thin.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-PretendardThin",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${PretendardRegular.variable} ${PretendardMedium} ${PretendardBold.variable} ${PretendardBlack.variable} ${PretendardExtraBold.variable} ${PretendardExtraLight.variable} ${PretendardLight.variable} ${PretendardSemiBold.variable} ${PretendardThin.variable} ${PretendardMedium.variable} `}
      >
        {children}
      </body>
    </html>
  );
}
